export const QUESTIONS = [
  {c:'math',l:1,q:'What is 4 + 3?',a:['6','7','8','9'],x:1,h:'Count four, then three more.'},
  {c:'math',l:1,q:'What is 5 × 2?',a:['7','10','12','15'],x:1,h:'Two groups of five.'},
  {c:'math',l:2,q:'What is 8 × 7?',a:['48','54','56','64'],x:2,h:'Think 7×7, then add 7.'},
  {c:'math',l:2,q:'What is 72 ÷ 8?',a:['8','9','10','12'],x:1,h:'8 times what equals 72?'},
  {c:'math',l:3,q:'A $24 game is 25% off. What is the discount?',a:['$4','$6','$8','$12'],x:1,h:'25% is one fourth.'},
  {c:'math',l:4,q:'Solve: 3(x + 2) = 21',a:['3','5','7','9'],x:1,h:'Divide by 3 first.'},
  {c:'math',l:5,q:'What is 15% of 260?',a:['26','39','52','65'],x:1,h:'10% is 26 and 5% is 13.'},
  {c:'words',l:1,q:'Which word rhymes with CAT?',a:['Dog','Hat','Sun','Cup'],x:1,h:'Listen to the ending sound.'},
  {c:'words',l:2,q:'Which word means the opposite of ANCIENT?',a:['Old','Modern','Dusty','Broken'],x:1,h:'Think new or current.'},
  {c:'words',l:3,q:'Which sentence uses “their” correctly?',a:['Their going home.','Put it over their.','Their dog is friendly.','They left they’re shoes.'],x:2,h:'“Their” shows ownership.'},
  {c:'words',l:4,q:'What does “meticulous” most nearly mean?',a:['Careless','Very careful','Loud','Uncertain'],x:1,h:'A meticulous person notices tiny details.'},
  {c:'words',l:5,q:'Which is an example of irony?',a:['A fire station burns down.','A dog barks.','Rain falls in spring.','A clock tells time.'],x:0,h:'Look for an unexpected contrast.'},
  {c:'science',l:1,q:'Which animal is a mammal?',a:['Frog','Shark','Dolphin','Lizard'],x:2,h:'It breathes air and nurses its young.'},
  {c:'science',l:2,q:'Plants use sunlight to make food in a process called…',a:['Respiration','Photosynthesis','Evaporation','Erosion'],x:1,h:'“Photo” relates to light.'},
  {c:'science',l:3,q:'What is the chemical symbol for oxygen?',a:['Ox','O','Og','Oy'],x:1,h:'It is a single letter.'},
  {c:'science',l:4,q:'Which force keeps planets in orbit around the Sun?',a:['Magnetism','Friction','Gravity','Buoyancy'],x:2,h:'It attracts masses to one another.'},
  {c:'science',l:5,q:'Which organelle is the main site of ATP production?',a:['Nucleus','Ribosome','Mitochondrion','Golgi apparatus'],x:2,h:'Often called the powerhouse of the cell.'},
  {c:'world',l:1,q:'Which is the largest ocean?',a:['Atlantic','Pacific','Indian','Arctic'],x:1,h:'It lies between Asia and the Americas.'},
  {c:'world',l:2,q:'Which continent contains Egypt?',a:['Asia','Africa','Europe','South America'],x:1,h:'Think Nile River.'},
  {c:'world',l:3,q:'What is the capital of Japan?',a:['Kyoto','Seoul','Tokyo','Osaka'],x:2,h:'It is one of the world’s largest cities.'},
  {c:'world',l:4,q:'The Prime Meridian passes through which location?',a:['Greenwich','Rome','Cairo','Sydney'],x:0,h:'Longitude 0°.'},
  {c:'world',l:5,q:'Which country is completely surrounded by South Africa?',a:['Botswana','Lesotho','Namibia','Eswatini'],x:1,h:'It is a mountainous kingdom.'},
  {c:'history',l:1,q:'Who was the first U.S. president?',a:['Abraham Lincoln','George Washington','Thomas Jefferson','John Adams'],x:1,h:'His portrait is on the one-dollar bill.'},
  {c:'history',l:2,q:'The pyramids of Giza were built in ancient…',a:['Rome','Egypt','Greece','China'],x:1,h:'They stand near the Nile.'},
  {c:'history',l:3,q:'The U.S. Declaration of Independence was adopted in…',a:['1492','1776','1865','1914'],x:1,h:'Think July 4.'},
  {c:'history',l:4,q:'The Magna Carta was first issued in which country?',a:['France','England','Spain','Italy'],x:1,h:'King John agreed to it.'},
  {c:'history',l:5,q:'Which empire used Constantinople as its capital?',a:['Aztec','Byzantine','Mughal','Inca'],x:1,h:'It was the eastern continuation of the Roman Empire.'},
  {c:'bible',l:1,q:'Who built the ark?',a:['Moses','Noah','David','Peter'],x:1,h:'Genesis tells his story.'},
  {c:'bible',l:2,q:'Who defeated Goliath?',a:['David','Samson','Solomon','Joshua'],x:0,h:'He used a sling.'},
  {c:'bible',l:3,q:'How many books are in the Protestant Bible?',a:['39','66','72','80'],x:1,h:'39 Old Testament + 27 New Testament.'},
  {c:'bible',l:4,q:'Which Gospel begins with “In the beginning was the Word”?',a:['Matthew','Mark','Luke','John'],x:3,h:'It emphasizes the Word becoming flesh.'},
  {c:'bible',l:5,q:'Which New Testament letter contains the “armor of God” passage?',a:['Romans','Ephesians','Hebrews','James'],x:1,h:'Chapter 6.'}
];
